openapi: 3.0.0
info:
  title: Admin Service API
  description: >
    The Admin Service API provides endpoints for managing administrative operations within a system, offering tools for overseeing user accounts, permissions, and system settings. 
    It allows administrators to monitor and control various aspects of the system.
  version: 1.0.0
servers:
  - url: 'https://driver-service-810707138380.asia-south1.run.app'  
tags:
  - name: Admin 
    description: Endpoints related to administrative operations.
paths:
  /api/v1/admin/login:
    post:
      tags:
        - Admin
      summary: Admin Login
      description: Allows an admin to log in to the system.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Login successful
        '401':
          description: Unauthorized. Invalid credentials.
      security:
        - BearerAuth: []      
  /api/v1/admin/trip/{id}:
    get:
      tags:
        - Admin
      summary: Fetch trip details
      description: Retrieve details of a specific trip using its unique identifier.
      operationId: fetchTripDetails
      parameters:
        - name: id
          in: path
          required: true
          description: The unique identifier of the trip
          schema:
            type: string
            example: 2dfc960e-3b25-405e-80d5-905e000c9d09
      responses:
        '200':
          description: Trip details retrieved successfully
        '404':
          description: Trip not found
      security:
        - BearerAuth: []
  /api/v1/admin/trip/trips:
    post:
      tags:
        - Admin
      summary: Fetch trips
      description: Fetches a list of trips based on the provided search criteria, with pagination support.
      parameters:
        - name: offset
          in: query
          description: The number of items to skip before starting to collect the result set.
          required: true
          schema:
            type: integer
            example: 0
        - name: limit
          in: query
          description: The number of items to return.
          required: true
          schema:
            type: integer
            example: 10
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FetchTripsRequest'
      responses:
        '200':
          description: A list of trips.
        '400':
          description: Invalid input provided.
      security:
        - BearerAuth: []
  /api/v1/admin/drivers/{driver_id}/profile:
    get:
      tags:
        - Admin
      summary: Fetch a driver profile by ID
      operationId: fetchDriverProfile
      parameters:
        - name: driver_id
          in: path
          required: true
          schema:
            type: string
            example: be4c7719-5bcd-4eba-9321-cf81f692acc8
          description: Unique ID of the driver
      responses:
        '200':
          description: Successfully retrieved the driver profile
      security:
        - BearerAuth: []
    
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT    
  schemas:
    LoginRequest:
      type: object
      properties:
        email_id:
          type: string
          format: email
          example: mrsool@test.com
        password:
          type: string
          format: password
          example: '12345678'
      required:
        - email_id
        - password    
    FetchTripsRequest:
      type: object
      properties:
        searchValue:
          type: string
          description: The search criteria for fetching trips.
          example: 9
      required:
        - searchValue
    Trip:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        startDate:
          type: string
          format: date
        endDate:
          type: string
          format: date
  